LearningBase.Mvc/Areas/Administrator/Controllers/CourseController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using LearningBase.Core;
using LearningBase.Dto.Course;
using LearningBase.Mvc.Areas.Administrator.Models.Course;
using LearningBase.Mvc.Controllers;
using LearningBase.Mvc.Infrastructure;
using LearningBase.Mvc.Infrastructure.Presentation;
using LearningBase.ServiceContract.Course;
using LearningBase.ServiceContract.Course.Request;

namespace LearningBase.Mvc.Areas.Administrator.Controllers
{
    [Authorize(Roles = CoreConstant.Role.Administrator)]
    public class CourseController : LearningBaseControllerBase
    {
        #region Fields

        private readonly ICourseService _courseService;
        private readonly IModuleService _moduleService;

        #endregion

        #region Constructors

        public CourseController(IServerUtilityProvider serverUtilityProvider,
            ICourseService courseService,
            IModuleService moduleService)
            : base(serverUtilityProvider)
        {
            this._courseService = courseService;
            this._moduleService = moduleService;
        }

        #endregion

        #region Public Methods

        public ActionResult Index()
        {
            return this.PartialView("_Index");
        }

        [HttpPost]
        public ActionResult GetCourseGridJson(FormCollection formCollection)
        {
            return this.GetPagedSearchGridJson(formCollection,
                this._courseService.PagedSearch,
                delegate(ICollection<CourseDto> entities)
                {
                    var rowJsonData = new List<object>();
                    foreach (var entity in entities)
                    {
                        rowJsonData.Add(new
                        {
                            entity.Id,
                            entity.Code,
                            entity.Name,
                            entity.Description
                        });
                    }

                    return rowJsonData;
                });
        }

        public ActionResult Create()
        {
            var model = new CreatePartialVm
            {
                MaintenanceButtonRow = new MaintenanceButtonRow(MaintenanceButtonRow.Preset.CreateCancel)
            };

            return this.PartialView("_Create", model);
        }

        [HttpPost]
        public ActionResult Create(CreatePartialVm model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.GetErrorJson(this.GetModelStateError().ToArray());
            }

            var request = new SaveCourseRequest
            {
                CourseDto = new CourseDto
                {
                    Code = model.Code,
                    Name = model.Name,
                    Description = model.Description
                }
            };

            var response = this._courseService.Create(request);
            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            return this.GetBasicSuccessJson(response, response.DtoId);
        }

        [HttpGet]
        public ActionResult Edit(int courseId)
        {
            var response = this._courseService.Read(courseId);

            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            var model = new EditPartialVm
            {
                Id = response.Dto.Id,
                Code = response.Dto.Code,
                Name = response.Dto.Name,
                Description = response.Dto.Description,
                MaintenanceButtonRow = new MaintenanceButtonRow(MaintenanceButtonRow.Preset.SaveDeleteCancel)
            };

            this.PopulateAuditFieldValue(response.Dto, model);

            return this.PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(EditPartialVm model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.GetErrorJson(this.GetModelStateError().ToArray());
            }

            var request = new SaveCourseRequest
            {
                CourseDto = new CourseDto
                {
                    Id = model.Id,
                    Code = model.Code,
                    Name = model.Name,
                    Description = model.Description
                }
            };

            this.PopulateAuditFieldValue(model, request.CourseDto);

            var response = this._courseService.Edit(request);
            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            return this.GetBasicSuccessJson(response, response.DtoId);
        }

        [HttpPost]
        public ActionResult Delete(int courseId)
        {
            var response = this._courseService.Delete(courseId);

            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            return this.GetBasicSuccessJson();
        }

        [HttpGet]
        public ActionResult CourseEditor(int courseId)
        {
            var response = this._courseService.Read(courseId);
            var searchModulesReponse = this._moduleService.Search(courseId);

            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            var model = new CourseEditorPartialVm
            {
                CourseId = response.Dto.Id,
                Code = response.Dto.Code,
                Name = response.Dto.Name
            };

            var orderedList = searchModulesReponse.DtoCollection.OrderBy(item => item.SortingIndex);
            foreach (var moduleDto in orderedList)
            {
                model.ModuleDtos.Add(moduleDto);
            }

            return this.PartialView("_CourseEditor", model);
        }

        [HttpPost]
        public ActionResult AddModule(int courseId, string moduleName)
        {
            var request = new SaveModuleRequest
            {
                ModuleDto = new ModuleDto
                {
                    CourseId = courseId,
                    Name = moduleName
                }
            };

            var response = this._moduleService.Create(request);

            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            return this.Json(new {IsSuccess = true, ModuleId = response.DtoId});
        }

        [HttpPost]
        public ActionResult EditModuleName(int courseId, int moduleId, string moduleName)
        {
            var response = this._moduleService.EditName(moduleId, courseId, moduleName);

            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            return this.GetBasicSuccessJson();
        }

        [HttpPost]
        public ActionResult DeleteModule(int moduleId)
        {
            var response = this._moduleService.Delete(moduleId);

            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            return this.GetBasicSuccessJson();
        }

        [HttpPost]
        public ActionResult UpdateIndex(int moduleId, int sortingIndex)
        {
            var response = this._moduleService.UpdateIndex(moduleId, sortingIndex);

            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            return this.GetBasicSuccessJson();
        }

        #endregion
    }
}

LearningBase.Mvc/Areas/Administrator/Controllers/StudentController.cs
using System.Collections.Generic;
using System.Linq;
using LearningBase.Core;
using LearningBase.Dto.Common;
using LearningBase.Mvc.Areas.Administrator.Models.Student;
using LearningBase.Mvc.Controllers;
using LearningBase.Mvc.Infrastructure;
using LearningBase.Mvc.Infrastructure.Presentation;
using LearningBase.ServiceContract.Common;
using LearningBase.ServiceContract.Common.Request;
using LearningBase.ServiceContract.Course;
using System.Web.Mvc;

namespace LearningBase.Mvc.Areas.Administrator.Controllers
{
    [Authorize(Roles = CoreConstant.Role.Administrator)]
    public class StudentController : LearningBaseControllerBase
    {
        #region Fields

        private readonly IStudentService _studentService;
        private readonly ICourseService _courseService;

        #endregion

        #region Constructors

        public StudentController(IServerUtilityProvider serverUtilityProvider,
            IStudentService studentService,
            ICourseService courseService)
            : base(serverUtilityProvider)
        {
            this._studentService = studentService;
            this._courseService = courseService;
        }

        #endregion

        #region Public Methods

        public ActionResult Index()
        {
            return this.PartialView("_Index");
        }

        [HttpPost]
        public ActionResult GetStudentGridJson(FormCollection formCollection)
        {
            return this.GetPagedSearchGridJson(formCollection,
                this._studentService.PagedSearch,
                delegate(ICollection<StudentDto> entities)
                {
                    var rowJsonData = new List<object>();
                    foreach (var entity in entities)
                    {
                        rowJsonData.Add(new
                        {
                            entity.Id,
                            entity.UserName,
                            entity.EmailAddress,
                            CreatedDateTime =
                                DateTimeManager.UtcToLocalDateTime(CoreConstant.Setting.DefaultLocalTimeZoneId,
                                    entity.CreatedDateTime).ToString(CoreConstant.Setting.DefaultLongDateFormat)
                        });
                    }

                    return rowJsonData;
                });
        }

        public ActionResult Create()
        {
            var model = new CreatePartialVm
            {
                CourseSelectList = this.GetCourseSelectList(),
                MaintenanceButtonRow = new MaintenanceButtonRow(MaintenanceButtonRow.Preset.CreateCancel)
            };

            return this.PartialView("_Create", model);
        }

        [HttpPost]
        public ActionResult Create(CreatePartialVm model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.GetErrorJson(this.GetModelStateError().ToArray());
            }

            var request = new CreateStudentRequest
            {
                StudentDto = new StudentDto
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    EmailAddress = model.EmailAddress,
                    UserName = model.UserName,
                    CourseId = model.CourseId
                },
                PrimaryUserPassword = model.Password
            };

            var response = this._studentService.Create(request);
            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            return this.GetBasicSuccessJson(response, response.DtoId);
        }

        [HttpGet]
        public ActionResult Edit(int studentId)
        {
            var response = this._studentService.Read(studentId);

            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            var model = new EditPartialVm
            {
                Id = response.Dto.Id,
                FirstName = response.Dto.FirstName,
                LastName = response.Dto.LastName,
                EmailAddress = response.Dto.EmailAddress,
                UserId = response.Dto.UserId,
                UserName = response.Dto.UserName,
                CourseSelectList = this.GetCourseSelectList(),
                CourseId = response.Dto.CourseId,
                MaintenanceButtonRow = new MaintenanceButtonRow(MaintenanceButtonRow.Preset.SaveDeleteCancel)
            };

            this.PopulateAuditFieldValue(response.Dto, model);

            return this.PartialView("_Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(EditPartialVm model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.GetErrorJson(this.GetModelStateError().ToArray());
            }

            var request = new EditStudentRequest
            {
                StudentDto = new StudentDto
                {
                    Id = model.Id,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    EmailAddress = model.EmailAddress,
                    UserId = model.UserId,
                    CourseId = model.CourseId
                }
            };

            this.PopulateAuditFieldValue(model, request.StudentDto);

            var response = this._studentService.Edit(request);
            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            return this.GetBasicSuccessJson(response, response.DtoId);
        }

        [HttpPost]
        public ActionResult Delete(int studentId)
        {
            var response = this._studentService.Delete(studentId);

            if (response.IsError())
            {
                return this.GetErrorJson(response);
            }

            return this.GetBasicSuccessJson();
        }

        #endregion

        #region Private Methods

        private SelectList GetCourseSelectList()
        {
            var response = this._courseService.GetAll();

            var studentPackages =
                response.DtoCollection.Select(
                    item => new {item.Id, item.Name});
            return new SelectList(studentPackages, "Id", "Name");
        }

        #endregion
    }
}

LearningBase.Mvc/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>LearningBase</title>
    @Styles.Render("~/bundles/sbadmin-css")
</head>
<body class="handle--not-loaded">
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand brand" href="#">LearningBase - Administration</a>
        </div>
        <!-- /.navbar-header -->
        <ul class="nav navbar-top-links navbar-right">
            @*@{
                var isOfflineMode = false;
                var offlineFilePath = this.Server.MapPath(OfflineFileData.OfflineFilePath);
                if (File.Exists(offlineFilePath))
                {
                    isOfflineMode = true;
                }
            }
            @if (isOfflineMode)
            {
                <li><label class="label label-warning">MAINTENANCE MODE</label></li>
            }*@
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        <a href="@Url.Action("Logout", "Account", new {area = string.Empty})"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="#" class="nav-ajax-menu" data-url="@Url.Action("Index", "Student", new {area = "Administrator"})"><i class="fa fa-user fa-fw"></i> @Resource.AdministratorMenu_Student </a>
                    </li>
                    <li>
                        <a href="#" class="nav-ajax-menu" data-url="@Url.Action("Index", "Course", new {area = "Administrator"})"><i class="fa fa-mortar-board fa-fw"></i> @Resource.AdministratorMenu_Course </a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <!-- Page Content -->
    <div id="page-wrapper" style="min-height: 576px;">
        <div class="container-fluid" id="mainUserContent">
            @RenderBody()
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

@{ Html.RenderPartial("_CommonLoadingDialog"); }
@Scripts.Render("~/bundles/sbadmin-js")
@Scripts.Render("~/bundles/e2l-form-js")
@Scripts.Render("~/bundles/admin-js")

<script>
    $(document)
        .ready(function() {
            var sidebar = new Sidebar();
            sidebar.Register();

            var topbar = new Topbar();
            topbar.Register();
        });
</script>

@RenderSection("scripts", false)

</body>

</html>

LearningBase.Mvc/Views/Shared/_AuditField.cshtml
@model LearningBase.Mvc.ViewModel.AuditableViewModelBase

@Html.HiddenFor(model => model.CreatedBy)
@Html.HiddenFor(model => model.CreatedDateTime)
@Html.HiddenFor(model => model.LastModifiedBy)
@Html.HiddenFor(model => model.LastModifiedDateTime)

LearningBase.Mvc/Views/Shared/_CommonLoadingDialog.cshtml
<div id="processingDialogPane" class="modal modal--loading fade in">
    <div class="modal-dialog normal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <span class="icon fa fa-refresh fa-spin"></span>
                Processing, please wait...
            </div>
        </div>
    </div>
</div>

<div id="loadingDialogPane" class="modal modal--loading fade in">
    <div class="modal-dialog normal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <span class="icon fa fa-refresh fa-spin"></span>
                Processing, please wait...
            </div>
        </div>
    </div>
</div>

LearningBase.Mvc/Views/Shared/_OuterPageLayout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LearningBase</title>

    @Styles.Render("~/bundles/sbadmin-css")

</head>

<body class="login handle--not-loaded">

    @RenderBody()

    @{ Html.RenderPartial("_CommonLoadingDialog"); }

    @Scripts.Render("~/bundles/sbadmin-js")
    @Scripts.Render("~/bundles/outerpage-js")

    @RenderSection("scripts", false)

</body>

</html>

LearningBase.Mvc/Views/Shared/_StudentLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>LearningBase</title>
    @Styles.Render("~/bundles/sbadmin-css")
</head>
<body class="handle--not-loaded">
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand brand" href="#">LearningBase</a>
        </div>
        <!-- /.navbar-header -->
        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li>
                        <a href="@Url.Action("Logout", "Account", new {area = string.Empty})"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li id="profile">
                        <div class="user__container">
                            <div class="avatar">
                                <a href="#" onclick="changeProfilePicture()"><img src="@Url.Content("~/Images/DefaultAvatar.png")" class="img-responsive" id="profile-picture" alt="Profile Picture"></a>
                            </div>
                            <div class="user__name" id="student-name"></div>
                            <div class="user__info" id="course-name"></div>
                        </div>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <!-- Page Content -->
    <div id="page-wrapper" style="min-height: 576px;">
        <div class="container-fluid" id="mainUserContent">
            @RenderBody()
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

@{ Html.RenderPartial("_CommonLoadingDialog"); }
@Scripts.Render("~/bundles/sbadmin-js")
@Scripts.Render("~/bundles/e2l-form-js")
@Scripts.Render("~/bundles/student-js")

<script>
    $(document)
        .ready(function () {
            refreshProfile();

            var sidebar = new Sidebar();
            sidebar.Register();

            var topbar = new Topbar();
            topbar.Register();
        });

    function refreshProfile() {
        setTimeout(function() {
            $.ajax({
                cache: false,
                async: true,
                type: "POST",
                url: '@Url.Action("GetProfile", "Home", new { area = "Student" })',
                success: function (data) {
                    $("#profile-picture").attr("src", data.Value.ProfilePictureUri);
                    if (data.Value.ProfilePictureName === null || data.Value.ProfilePictureName === "") {
                        $("#profile-picture").attr("src","@Url.Content("~/Images/DefaultAvatar.png")");
                    }
                    $("#student-name").empty();
                    $("#student-name").html(data.Value.StudentName);
                    $("#course-name").empty();
                    $("#course-name").html(data.Value.CourseName);
                }
            });
        }, 300);
    }

</script>

@RenderSection("scripts", false)

</body>

</html>